version: '0'
services:
  hexo:
    container_name: hexo
    image: fengyao/hexo:release-v0.05.0601
    restart: always
    environment:
      - GIT_USER=yaoelvon
      - GIT_EMAIL=yaoelvon@gmail.com
    volumes:
      - ./:/mnt
      - $HOME/.ssh:/root/.ssh
  nginx:
    container_name: blog
    image: nginx:alpine
    restart: always
    volumes:
      - ./public:/usr/share/nginx/html:ro
    ports:
      - "4000:80"